### ISSUE TITLE
No "medical" demo

### ISSUE THREAD

**Issue by racineda** [oceanwp/oceanwp-sample-data#1]
There does not appear to be a "medical" demo here. It is a clear omission based on the demo page here: https://oceanwp.org/demos/

**Comment by nicolas-owp** [comment]
Hello, the Medical demo is a Pro demo, like all pro demos, you need to have the Core Extensions Bundle, then, install on your site the Ocean Pro Demos plugin, you will have all demos on Theme Panel > Install Demos.
